version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'prisma'
      POSTGRES_PASSWORD: 'prisma123'
      POSTGRES_DB: 'notes'
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://prisma:prisma123@postgres:5432/notes'
      JWT_SECRET: ${JWT_SECRET}

