name: prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  main-mobile:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Run detekt
        run: ./gradlew :app:detekt

  main-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build
